name: Docker Login Test

on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Cheeckout repo
      - uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "Login successful!"

      # Build the Docker images by calling docker-compose
      - name: Build Docker images
        run: docker-compose build
        env: # Pass the secrets
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # Push the Docker images to Docker Hub
      - name: Push Docker images
        run: |
          docker-compose push backend
          docker-compose push frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
