name: Docker Login Test

on:
  workflow_dispatch:

jobs:
  test_docker_login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "Login successful!"

      - name: Check Docker Info
        run: |
          docker info
